# Generated by Django 4.2.5 on 2023-09-13 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTVColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Brand name', max_length=50, verbose_name='Brand')),
                ('style', models.CharField(help_text='Style description', max_length=50, verbose_name='Style')),
                ('name', models.CharField(help_text='Color name', max_length=50, verbose_name='Color Name')),
                ('hex', models.CharField(help_text='Hexadecimal color code (e.g., "#RRGGBB")', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., "#RRGGBB")', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Hex Color Code')),
                ('r', models.PositiveSmallIntegerField(help_text='Red component (0-255)', validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than or equal to 0'), django.core.validators.MaxValueValidator(255, 'Value must be less than or equal to 255')], verbose_name='Red Component')),
                ('g', models.PositiveSmallIntegerField(help_text='Green component (0-255)', validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than or equal to 0'), django.core.validators.MaxValueValidator(255, 'Value must be less than or equal to 255')], verbose_name='Green Component')),
                ('b', models.PositiveSmallIntegerField(help_text='Blue component (0-255)', validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than or equal to 0'), django.core.validators.MaxValueValidator(255, 'Value must be less than or equal to 255')], verbose_name='Blue Component')),
            ],
        ),
    ]
