# Generated by Django 4.2.5 on 2023-09-13 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTVColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Brand name', max_length=50, verbose_name='Brand')),
                ('style', models.CharField(help_text='Style description', max_length=50, verbose_name='Style')),
                ('name', models.CharField(help_text='Color name', max_length=50, verbose_name='Color Name')),
                ('hex', models.CharField(help_text='Hexadecimal color code (e.g., "#RRGGBB")', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., "#RRGGBB")', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Hex Color Code')),
            ],
        ),
        migrations.DeleteModel(
            name='HTVColors',
        ),
    ]
