# Generated by Django 4.2.5 on 2023-09-13 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_htvcolor_delete_htvcolors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htvcolor',
            name='hex',
            field=models.CharField(help_text='Hexadecimal color code (e.g., "#RRGGBB")', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., "#RRGGBB")', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Hex Color Code'),
        ),
    ]
