# Generated by Django 4.2.5 on 2023-09-14 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_htvcolor_hex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='htvcolor',
            old_name='hex',
            new_name='hex_code',
        ),
    ]
